In [ ]:
###4.	Pandas Data Manipulation
# –	Given a CSV file with sales data (sales.csv), perform the following tasks:
# •	Load the data into a Pandas DataFrame.
# •	Calculate the total sales for each product category.
# •	Find the top 5 products with the highest sales


In [1]:
# mount the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


##Load the CSV data into a Pandas DataFrame:


In [23]:
import pandas as pd

# Load the data from the CSV file
csv_file_path = '/content/Sample_Sales_Data.csv'  # Update the path if needed
sales_data = pd.read_csv(csv_file_path)

# Display the first few rows of the DataFrame
print(sales_data.head())


   ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
0        101     Electronics      Laptop            50          1000   
1        102     Electronics  Smartphone           150           800   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
4        105        Clothing     T-shirt           100            20   

   TotalSales  
0       50000  
1      120000  
2       10000  
3        9000  
4        2000  


##Calculate the total sales for each product category:

In [24]:
# Calculate the total sales for each product category
total_sales_by_category = sales_data.groupby('ProductCategory')['TotalSales'].sum().reset_index()

# Display the result
print("Total Sales by Product Category:")
print(total_sales_by_category)


Total Sales by Product Category:
  ProductCategory  TotalSales
0        Clothing        6800
1     Electronics      186000
2       Furniture       21250


##Find the top 5 products with the highest sales:

In [26]:
top_5_products_sort = sales_data.sort_values(by='TotalSales', ascending=False).head()
print("\nTop 5 Products with the Highest Sales (sort_values):")
print(top_5_products_sort)


Top 5 Products with the Highest Sales (sort_values):
   ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
1        102     Electronics  Smartphone           150           800   
0        101     Electronics      Laptop            50          1000   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
9        110     Electronics     Monitor            45           200   

   TotalSales  
1      120000  
0       50000  
2       10000  
3        9000  
9        9000  


In [27]:
top_5_products_sort

ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
1        102     Electronics  Smartphone           150           800   
0        101     Electronics      Laptop            50          1000   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
9        110     Electronics     Monitor            45           200   

   TotalSales  
1      120000  
0       50000  
2       10000  
3        9000  
9        9000

In [28]:
top_5_products.head()

ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
1        102     Electronics  Smartphone           150           800   
0        101     Electronics      Laptop            50          1000   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
9        110     Electronics     Monitor            45           200   

   TotalSales  
1      120000  
0       50000  
2       10000  
3        9000  
9        9000

In [29]:
sales_data.head()

ProductID ProductCategory ProductName  QuantitySold  PricePerUnit  \
0        101     Electronics      Laptop            50          1000   
1        102     Electronics  Smartphone           150           800   
2        103       Furniture        Sofa            20           500   
3        104       Furniture       Table            30           300   
4        105        Clothing     T-shirt           100            20   

   TotalSales  
0       50000  
1      120000  
2       10000  
3        9000  
4        2000

5.	Numpy Array Operations

–	Create a 3x3 NumPy array with random integers. Perform the following operations:
•	Compute the sum of all elements in the array.
•	Find the mean and standard deviation of the elements.
•	Normalize the array (subtract the mean and divide by the standard deviation).


In [30]:
# Step 1: Create a 3x3 NumPy array with random integers
import numpy as np
array = np.random.randint(1, 100, size=(3, 3))
print("Original Array:")
print(array)

Original Array:
[[89 97 47]
 [96 10 17]
 [ 3 53 31]]


In [31]:
# Step 2: Compute the sum of all elements in the array
array_sum = np.sum(array)
print("\nSum of all elements:", array_sum)


Sum of all elements: 443


In [32]:
# Step 3: Find the mean and standard deviation of the elements
array_mean = np.mean(array)
array_std = np.std(array)
print("Mean of elements:", array_mean)
print("Standard Deviation of elements:", array_std)

Mean of elements: 49.22222222222222
Standard Deviation of elements: 35.14660653060668


In [33]:
# Step 4: Normalize the array (subtract the mean and divide by the standard deviation)
normalized_array = (array - array_mean) / array_std
print("\nNormalized Array:")
print(normalized_array)


Normalized Array:
[[ 1.13176724  1.35938523 -0.06322722]
 [ 1.33093298 -1.11596043 -0.91679469]
 [-1.31512618  0.10748627 -0.5184632 ]]
